server:
  port: 9009
spring:
  application:
    name: tensquare-sms
  rabbitmq:
    host: 192.168.135.130
aliyun:
  sms:
    accessKeyId: LTAI4Fg8L85rdzg2BLuLNkXJ
    accessKeySecret: NktFIYhARLoRr8BUQsT6oJFQN0psTr
    template_code: SMS_175425030
    sign_name: 青风平台